"""initial_schema

Revision ID: 0ee18eb5fe30
Revises: 
Create Date: 2026-03-30 17:35:16.614318

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ee18eb5fe30'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('obras',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('direccion', sa.String(length=300), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('activa', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trabajadores',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('obra_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('cedula', sa.String(length=20), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('cargo', sa.String(length=100), nullable=False),
    sa.Column('especialidad', sa.String(length=50), nullable=False),
    sa.Column('valor_dia', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['obra_id'], ['obras.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cedula', name='uq_trabajador_cedula')
    )
    op.create_index(op.f('ix_trabajadores_obra_id'), 'trabajadores', ['obra_id'], unique=False)
    op.create_table('asistencias',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trabajador_id', sa.Integer(), nullable=False),
    sa.Column('registrado_por', sa.Integer(), nullable=True),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('observacion', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("estado IN ('presente', 'ausente', 'incapacidad', 'permiso', 'dia_festivo')", name='ck_asistencia_estado_valido'),
    sa.ForeignKeyConstraint(['registrado_por'], ['trabajadores.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['trabajador_id'], ['trabajadores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trabajador_id', 'fecha', name='uq_asistencia_trabajador_fecha')
    )
    op.create_index(op.f('ix_asistencias_fecha'), 'asistencias', ['fecha'], unique=False)
    op.create_index(op.f('ix_asistencias_trabajador_id'), 'asistencias', ['trabajador_id'], unique=False)
    op.create_table('gastos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('obra_id', sa.Integer(), nullable=False),
    sa.Column('registrado_por_id', sa.Integer(), nullable=True),
    sa.Column('proveedor', sa.String(length=200), nullable=True),
    sa.Column('nit', sa.String(length=20), nullable=True),
    sa.Column('numero_factura', sa.String(length=50), nullable=True),
    sa.Column('fecha_factura', sa.Date(), nullable=True),
    sa.Column('total', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('categoria', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('imagen_path', sa.String(length=500), nullable=True),
    sa.Column('texto_ocr_raw', sa.Text(), nullable=True),
    sa.Column('confianza_ocr', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("estado IN ('pendiente', 'procesado', 'validado', 'rechazado')", name='ck_gasto_estado_valido'),
    sa.CheckConstraint('total >= 0', name='ck_gasto_total_positivo'),
    sa.ForeignKeyConstraint(['obra_id'], ['obras.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['registrado_por_id'], ['trabajadores.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gastos_estado'), 'gastos', ['estado'], unique=False)
    op.create_index(op.f('ix_gastos_obra_id'), 'gastos', ['obra_id'], unique=False)
    op.create_table('nominas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trabajador_id', sa.Integer(), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_fin', sa.Date(), nullable=False),
    sa.Column('dias_trabajados', sa.Integer(), nullable=False),
    sa.Column('valor_dia_snapshot', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_pagar', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('dias_trabajados >= 0', name='ck_nomina_dias_positivos'),
    sa.CheckConstraint('total_pagar >= 0', name='ck_nomina_total_positivo'),
    sa.ForeignKeyConstraint(['trabajador_id'], ['trabajadores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nominas_trabajador_id'), 'nominas', ['trabajador_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_nominas_trabajador_id'), table_name='nominas')
    op.drop_table('nominas')
    op.drop_index(op.f('ix_gastos_obra_id'), table_name='gastos')
    op.drop_index(op.f('ix_gastos_estado'), table_name='gastos')
    op.drop_table('gastos')
    op.drop_index(op.f('ix_asistencias_trabajador_id'), table_name='asistencias')
    op.drop_index(op.f('ix_asistencias_fecha'), table_name='asistencias')
    op.drop_table('asistencias')
    op.drop_index(op.f('ix_trabajadores_obra_id'), table_name='trabajadores')
    op.drop_table('trabajadores')
    op.drop_table('obras')
    # ### end Alembic commands ###
